---

- name: Ensure HTTPS is enabled for apt.
  stat: path=/usr/lib/apt/methods/https
  register: apt_https

- name: Install HTTPS transport for apt.
  apt: pkg=apt-transport-https state=installed
  when: not apt_https.stat.exists

- name: Update repositories.
  apt: update_cache=yes cache_valid_time={{ aptcachetime }}

- name: Install common packages.
  apt:
    pkg:
      - curl
      - net-tools
      - wget
      - atop
      - net-tools
      - vim
      - git
      - rsync
      - nfs-common
      - unzip
      - whois
      - zip
      - pwgen
      - pv
      - openssl
      - nmap
      - screen
      - tmux
      - rar
    state: latest

- name: Upgrade installed pkgs.
  apt: upgrade=yes
